spring:
  docker:
    compose:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:1337/realms/springboothtmx
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: springboothtmx-client
            client-name: springboothtmx-client
            client-secret: ymz4ik66K0r5U6mcgE6TMg4cSzZO0bSj
            scope:
              - openid
              - offline_access
              - profile
            authorization-grant-type: authorization_code
  datasource:
    url: jdbc:postgresql://localhost:1339/springboothtmx
    username: springboothtmx
    password: springboothtmx
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
logging:
  level:
    org:
      springframework:
        security: DEBUG

