spring:
  docker:
    compose:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-name: springboothtmx-client
            client-id: springboothtmx-client
            client-secret: QQAeT15xHd99PhJuPp6hBOhZRz3WYHVv
            authorization-grant-type: authorization_code
            scope: openid,offline_access,profile
        provider:
          keycloak:
            issuer-uri: http://localhost:1337/realms/SpringBootHtmx
            user-name-attribute: preferred_username
  datasource:
    url: jdbc:postgresql://localhost:1339/springboothtmx
    username: springboothtmx
    password: s pringboothtmx
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
logging:
  level:
    org:
      springframework:
        security: DEBUG

